apiVersion: batch/v1
kind: Job
metadata:
  name: copy-content-job
spec:
  template:
    spec:
      containers:
      - name: file-copy
        image: busybox
        command: ["sh", "-c"]
        args:
          - "echo '<h1>Hello World!</h1>' > /mnt/index.html"
        volumeMounts:
        - mountPath: "/mnt"
          name: nfs-volume
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      restartPolicy: OnFailure

